### ISSUE TITLE
How To Scaffold Es6 and TypeScript Project?

### ISSUE THREAD

**Issue by JimLynchCodes** [samme/brunch-phaser#1]
Hi, I also asked this [here](http://www.html5gamedevs.com/topic/28433-brunch-with-phaser-starter-project/).

Basically, when I run `brunch new -s samme/brunch-phaser` I get an es5 project. It would be great if you could pass another flag like es5, es6, typescript, etc and then have the generator scaffold out a project with default files in each that specific style of javascript. 

Does something like this exist already and I'm just missing it? Why does it say "You _can_ use CoffeeScript, ES6, TypeScript, or plain JavaScript"? Is there an example of how to use them? thanks!

**Comment by samme** [comment]
You have to either convert the sample app files or replace them (in your choice language). It's a bit of a drawback.

For es6 I think you can do

```
npm install -g lebab
lebab --replace app/
```

If you do this a lot you'll probably want to just copy and modify the skeleton, then use

```
brunch new <project> -s path-to-modified-brunch-phaser
```

I can maybe make a branch for each language to help people get started.

**Comment by samme** [comment]
See <https://github.com/samme/brunch-phaser/blob/master/README.md#clone>
